exec DWH_MAIN_PROCEDURE(TO_DATE('1990-01-01', 'YYYY-MM-DD'));

SELECT * FROM STG_WT_CV_JOB_HISTORY_1_READY ORDER BY PIN, START_DATE DESC;

SELECT * FROM STG_WT_CV_JOB_HISTORY_1 ORDER BY PIN, START_DATE DESC;

SELECT COUNT(*) FROM WT_CV_JOB_HISTORY_1 ORDER BY PIN, START_DATE DESC;

SET SERVEROUTPUT ON;

