PROMPT ##############################################################
PROMPT ###### - Referential Information System - ####################
PROMPT ############### - CREATE TABLE - #############################
PROMPT ################# - R_LOG - ##################################

CREATE TABLE RIS.R_LOG
(
ID_LOG number(16) GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
LOG_TIME timestamp DEFAULT SYSTIMESTAMP,
MODULE varchar2(128 CHAR),
OPERATION varchar2(128 CHAR),
STATUS varchar2(128 CHAR),
CONSTRAINT R_LG_ID_LOG_PK PRIMARY KEY (ID_LOG) USING INDEX (CREATE INDEX RIS.R_LG_ID_LOG_PK_IDX ON RIS.R_LOG(ID_LOG) TABLESPACE RIS_INDEX)
)
TABLESPACE RIS_DATA
;

COMMENT ON TABLE RIS.R_WORKER IS 'Workers';
COMMENT ON TABLE RIS.R_LOG IS 'Logging';
COMMENT ON COLUMN RIS.R_LOG.ID_LOG IS 'PK - Log ID';
COMMENT ON COLUMN RIS.R_LOG.LOG_TIME IS 'Timestamp';
COMMENT ON COLUMN RIS.R_LOG.MODULE IS 'Package which wrote the log';
COMMENT ON COLUMN RIS.R_LOG.OPERATION IS 'Exact operation';
COMMENT ON COLUMN RIS.R_LOG.STATUS IS 'Status of current operation';

