create or replace procedure RIS.R_LOG_SP(MODULE_IN IN varchar, OPERATION_IN IN varchar, STATUS_IN IN varchar) IS
	PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
	INSERT INTO R_LOG(LOG_TIME, MODULE, OPERATION, STATUS) VALUES (SYSTIMESTAMP, MODULE_IN, OPERATION_IN, STATUS_IN);
	COMMIT;
EXCEPTION
	WHEN OTHERS 	
		THEN
			DBMS_OUTPUT.PUT_LINE('Error logging: ' || SQLCODE || ' - ' || SQLERRM);
END;
/