CREATE OR REPLACE PROCEDURE RIS_DWH.DWH_ERROR_LOG_SP(
    TABLE_NAME_IN IN VARCHAR2,
    VERIFY_COL_IN IN VARCHAR2,
    ROW_ID_IN IN VARCHAR2,
    STATUS_IN IN VARCHAR2,
    ERROR_MSG_IN IN VARCHAR2
) IS
	PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
	INSERT INTO ETL_ERROR_LOG(LOG_TIME, TABLE_NAME, VERIFY_COL, ROW_ID, STATUS, ERROR_MSG)
	VALUES (SYSTIMESTAMP, TABLE_NAME_IN, VERIFY_COL_IN, ROW_ID_IN, STATUS_IN, ERROR_MSG_IN);
	COMMIT;
EXCEPTION
	WHEN OTHERS
		THEN
			DBMS_OUTPUT.PUT_LINE('Error logging: ' || SQLCODE || ' - ' || SQLERRM);
END;
/