PROMPT ##############################################################
PROMPT ###### - Referential Information System - ####################
PROMPT ############### - CREATE TABLES - ############################
PROMPT ################# - WORKER - #################################

CREATE TABLE RIS.R_WORKER_P
(
PIN number(16),
NAME varchar2(128 CHAR),
SURNAME varchar2(128 CHAR),
V_NAME varchar2(128 CHAR),
V_SURNAME varchar2(128 CHAR),
DOB DATE,
EMAIL varchar2(288 CHAR),
M_F char(1 CHAR),
ID_WS number(16),
REG_DATE DATE,
STATUS char(1) DEFAULT 'A',
ID_TOFI number(12) INVISIBLE,
CONSTRAINT R_WRP_PIN_PK_IDX PRIMARY KEY (PIN) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_WRP_WS_FK FOREIGN KEY (ID_WS)
	REFERENCES GSD.G_WORKER_STATUS(ID_WS),
CONSTRAINT R_WRP_EMAIL_UQ UNIQUE (EMAIL),
CONSTRAINT R_WRP_M_F_CHK CHECK (M_F IN ('M', 'F')),
CONSTRAINT R_WRP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W'))      
)
PARTITION BY RANGE (PIN)
(
PARTITION R_WR_PART_01 VALUES LESS THAN (100000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_02 VALUES LESS THAN (200000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_03 VALUES LESS THAN (300000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_04 VALUES LESS THAN (400000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_05 VALUES LESS THAN (500000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_06 VALUES LESS THAN (600000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_07 VALUES LESS THAN (700000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_08 VALUES LESS THAN (800000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_09 VALUES LESS THAN (900000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_10 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_11 VALUES LESS THAN (1100000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_12 VALUES LESS THAN (1200000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_13 VALUES LESS THAN (1300000) TABLESPACE RIS_DATA,
PARTITION R_WR_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_WORKER_P RENAME CONSTRAINT R_WRP_PIN_PK_IDX TO R_WRP_PIN_PK;


PROMPT ################# - COMPANY - ############################

CREATE TABLE RIS.R_COMPANY_P
(
CIN number(16),               
NAME varchar2(256 CHAR),
ID_CMPT number(16),
DOI date,
DOE date,
EMAIL varchar2(288 CHAR),
REG_DATE date,
STATUS char(1) DEFAULT 'A',
CONSTRAINT R_COMPP_CIN_PK_IDX PRIMARY KEY (CIN) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_COMPP_CIN_ID_CMPT_FK FOREIGN KEY (ID_CMPT)
    REFERENCES GSD.G_COMPANY_TYPE (ID_CMPT),
CONSTRAINT R_COMPP_EMAIL_UQ UNIQUE (EMAIL),
CONSTRAINT R_COMPP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W'))
)
PARTITION BY RANGE (CIN)
(
PARTITION R_COMP_PART_01 VALUES LESS THAN (500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_02 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_03 VALUES LESS THAN (1500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_04 VALUES LESS THAN (2000000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_05 VALUES LESS THAN (2500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_06 VALUES LESS THAN (3000000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_07 VALUES LESS THAN (3500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_08 VALUES LESS THAN (4000000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_09 VALUES LESS THAN (4500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_10 VALUES LESS THAN (5000000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_11 VALUES LESS THAN (5500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_12 VALUES LESS THAN (6000000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_13 VALUES LESS THAN (6500000) TABLESPACE RIS_DATA,
PARTITION R_COMP_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_COMPANY_P RENAME CONSTRAINT R_COMPP_CIN_PK_IDX TO R_COMPP_CIN_PK;


PROMPT ################# - CV - #################################

CREATE TABLE RIS.R_CV_P
(
ID_CV number(16),
PIN number(16),
NAME varchar2(256 CHAR),
CREATED_DATE date,
VISIBLE number(1) DEFAULT 1,
STATUS char(1) DEFAULT 'A',
CONSTRAINT R_CVP_ID_CV_PK_IDX PRIMARY KEY (ID_CV) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_CVP_PIN_FK FOREIGN KEY (PIN)
  REFERENCES RIS.R_WORKER_P(PIN),
CONSTRAINT R_CVP_CREATED_DATE_NN CHECK (CREATED_DATE IS NOT NULL),
CONSTRAINT R_CVP_VISIBLE_CHK CHECK (VISIBLE IN (0, 1)),
CONSTRAINT R_CVP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W'))
)
PARTITION BY RANGE (ID_CV)
(
PARTITION R_CV_PART_01 VALUES LESS THAN (100000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_02 VALUES LESS THAN (200000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_03 VALUES LESS THAN (300000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_04 VALUES LESS THAN (400000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_05 VALUES LESS THAN (500000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_06 VALUES LESS THAN (600000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_07 VALUES LESS THAN (700000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_08 VALUES LESS THAN (800000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_09 VALUES LESS THAN (900000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_10 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_11 VALUES LESS THAN (1100000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_12 VALUES LESS THAN (1200000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_13 VALUES LESS THAN (1300000) TABLESPACE RIS_DATA,
PARTITION R_CV_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_CV_P RENAME CONSTRAINT R_CVP_ID_CV_PK_IDX TO R_CVP_ID_CV_PK;

PROMPT ########## - EDU ORG - ############################

CREATE TABLE RIS.R_EDU_ORG_P
(
EIN number(16),               
NAME varchar2(256 CHAR),
DOI date,
DOE date,
EMAIL varchar2(288 CHAR),
REG_DATE date,
STATUS char(1) DEFAULT 'A',
CONSTRAINT R_EOP_EIN_PK_IDX PRIMARY KEY (EIN) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_EOP_EMAIL_UQ UNIQUE (EMAIL),
CONSTRAINT R_EOP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W'))
)
PARTITION BY RANGE (EIN)
(
PARTITION R_EO_PART_01 VALUES LESS THAN (500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_02 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_03 VALUES LESS THAN (1500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_04 VALUES LESS THAN (2000000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_05 VALUES LESS THAN (2500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_06 VALUES LESS THAN (3000000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_07 VALUES LESS THAN (3500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_08 VALUES LESS THAN (4000000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_09 VALUES LESS THAN (4500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_10 VALUES LESS THAN (5000000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_11 VALUES LESS THAN (5500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_12 VALUES LESS THAN (6000000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_13 VALUES LESS THAN (6500000) TABLESPACE RIS_DATA,
PARTITION R_EO_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_EDU_ORG_P RENAME CONSTRAINT R_EOP_EIN_PK_IDX TO R_EOP_EIN_PK;


PROMPT ########## - CV EDU HISTORY - ############################

CREATE TABLE RIS.R_CV_EDU_HIST_P
(
ID_CEH number(16),
ID_CV number(16),
EIN number(16),
ID_EFT number(16),
ID_TIT number(16) DEFAULT 30,
START_DATE date,
END_DATE date,
GRAD_DATE date,
CREATED_DATE date,
VISIBLE number(1) DEFAULT 1,
STATUS char(1) DEFAULT 'A',
CONSTRAINT R_CEHP_ID_CEH_PK_IDX PRIMARY KEY (ID_CEH) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_CEHP_ID_CV_FK FOREIGN KEY (ID_CV)
  REFERENCES RIS.R_CV_P (ID_CV),
CONSTRAINT R_CEHP_EIN_FK FOREIGN KEY (EIN)
  REFERENCES RIS.R_EDU_ORG_P (EIN),
CONSTRAINT R_CEHP_ID_EFT_FK FOREIGN KEY (ID_EFT)
  REFERENCES GSD.G_EDU_FIELD_TYPE (ID_EFT),
CONSTRAINT R_CEHP_ID_TIT_FK FOREIGN KEY (ID_TIT)
  REFERENCES GSD.G_TITLE (ID_TIT),
CONSTRAINT R_CEHP_START_END_CHCK CHECK (START_DATE < END_DATE),
CONSTRAINT R_CEHP_GRAD_DATE_CHCK CHECK (END_DATE <= GRAD_DATE),
CONSTRAINT R_CEHP_VISIBLE_CHK CHECK (VISIBLE IN (0, 1)),
CONSTRAINT R_CEHP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W'))
)
PARTITION BY RANGE (ID_CEH)
(
PARTITION R_CEH_PART_01 VALUES LESS THAN (200000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_02 VALUES LESS THAN (400000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_03 VALUES LESS THAN (600000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_04 VALUES LESS THAN (800000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_05 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_06 VALUES LESS THAN (1200000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_07 VALUES LESS THAN (1400000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_08 VALUES LESS THAN (1600000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_09 VALUES LESS THAN (1800000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_10 VALUES LESS THAN (2000000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_11 VALUES LESS THAN (2200000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_12 VALUES LESS THAN (2400000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_13 VALUES LESS THAN (2600000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_14 VALUES LESS THAN (2800000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_15 VALUES LESS THAN (3000000) TABLESPACE RIS_DATA,
PARTITION R_CEH_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_CV_EDU_HIST_P RENAME CONSTRAINT R_CEHP_ID_CEH_PK_IDX TO R_CEHP_ID_CEH_PK;


PROMPT ########## - CV JOB HISTORY - ############################

CREATE TABLE RIS.R_CV_JOB_HIST_P
(
ID_CJH number(16),
ID_CV number(16),
CIN number(16),
ID_JT number(16),
ID_JP number(16),
START_DATE date,
END_DATE date,
VISIBLE number(1) DEFAULT 1,
CREATED_DATE date,
STATUS char(1) DEFAULT 'A',
CONSTRAINT R_CJHP_ID_CJH_PK_IDX PRIMARY KEY (ID_CJH) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_CJHP_ID_CV_R_CV_FK FOREIGN KEY (ID_CV)
  REFERENCES RIS.R_CV_P(ID_CV),
CONSTRAINT R_CJHP_CIN_FK FOREIGN KEY (CIN)
  REFERENCES RIS.R_COMPANY_P (CIN),
CONSTRAINT R_CJHP_ID_JT_FK FOREIGN KEY (ID_JT)
  REFERENCES GSD.G_JOB_TYPE (ID_JT),
CONSTRAINT R_CJHP_ID_JP_FK FOREIGN KEY (ID_JP)
  REFERENCES GSD.G_JOB_POSITION (ID_JP),
CONSTRAINT R_CJHP_START_DATE_NN CHECK (START_DATE IS NOT NULL),
CONSTRAINT R_CJHP_END_DATE_CHK CHECK (END_DATE > START_DATE),
CONSTRAINT R_CJHP_VISIBLE_CHK CHECK (VISIBLE IN (0, 1)),
CONSTRAINT R_CJHP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W')) 
)
PARTITION BY RANGE (ID_CJH)
(
PARTITION R_CJH_PART_01 VALUES LESS THAN (200000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_02 VALUES LESS THAN (400000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_03 VALUES LESS THAN (600000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_04 VALUES LESS THAN (800000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_05 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_06 VALUES LESS THAN (1200000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_07 VALUES LESS THAN (1400000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_08 VALUES LESS THAN (1600000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_09 VALUES LESS THAN (1800000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_10 VALUES LESS THAN (2000000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_11 VALUES LESS THAN (2200000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_12 VALUES LESS THAN (2400000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_13 VALUES LESS THAN (2600000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_14 VALUES LESS THAN (2800000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_15 VALUES LESS THAN (3000000) TABLESPACE RIS_DATA,
PARTITION R_CJH_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_CV_JOB_HIST_P RENAME CONSTRAINT R_CJHP_ID_CJH_PK_IDX TO R_CJHP_ID_CJH_PK;

PROMPT ########## - CV JOB REFERENCE - ############################

CREATE TABLE RIS.R_CV_JOB_REFERENCE_P
(
ID_CJR number(16),
ID_CJH number(16),
REF_TEXT varchar2(512 CHAR),
REF_PIN number(16),
ID_EVT number(16),
REF_DATE DATE,
STATUS char(1) DEFAULT 'A',
CONSTRAINT R_CJRP_ID_CJR_PK_IDX PRIMARY KEY (ID_CJR) USING INDEX LOCAL TABLESPACE RIS_INDEX,
CONSTRAINT R_CJRP_ID_CJH_FK FOREIGN KEY (ID_CJH)
  REFERENCES RIS.R_CV_JOB_HIST_P (ID_CJH),
CONSTRAINT R_CJRP_REF_PIN_FK FOREIGN KEY (REF_PIN)
    REFERENCES RIS.R_WORKER_P(PIN),
CONSTRAINT R_CJRP_ID_EVT_FK FOREIGN KEY (ID_EVT)
	REFERENCES GSD.G_EVALUATION (ID_EVT),
CONSTRAINT R_CJRP_STATUS_CHK CHECK (STATUS IN ('A', 'D', 'W'))
)
PARTITION BY RANGE (ID_CJR)
(
PARTITION R_CJR_PART_01 VALUES LESS THAN (200000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_02 VALUES LESS THAN (400000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_03 VALUES LESS THAN (600000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_04 VALUES LESS THAN (800000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_05 VALUES LESS THAN (1000000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_06 VALUES LESS THAN (1200000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_07 VALUES LESS THAN (1400000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_08 VALUES LESS THAN (1600000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_09 VALUES LESS THAN (1800000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_10 VALUES LESS THAN (2000000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_11 VALUES LESS THAN (2200000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_12 VALUES LESS THAN (2400000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_13 VALUES LESS THAN (2600000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_14 VALUES LESS THAN (2800000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_15 VALUES LESS THAN (3000000) TABLESPACE RIS_DATA,
PARTITION R_CJR_PART_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE RIS_DATA
)
;

ALTER TABLE RIS.R_CV_JOB_REFERENCE_P RENAME CONSTRAINT R_CJRP_ID_CJR_PK_IDX TO R_CJRP_ID_CJR_PK;


INSERT INTO RIS.R_COMPANY_P(CIN, NAME, ID_CMPT, DOI, DOE, EMAIL, REG_DATE, STATUS) SELECT CIN, NAME, ID_CMPT, DOI, DOE, EMAIL, REG_DATE, STATUS FROM RIS.R_COMPANY;
INSERT INTO RIS.R_EDU_ORG_P(EIN, NAME, DOI, DOE, EMAIL, REG_DATE, STATUS) SELECT EIN, NAME, DOI, DOE, EMAIL, REG_DATE, STATUS FROM RIS.R_EDU_ORG;

INSERT INTO RIS.R_WORKER_P(PIN, NAME, SURNAME, V_NAME, V_SURNAME, DOB, EMAIL, M_F, ID_WS, REG_DATE, STATUS, ID_TOFI) 
SELECT PIN, NAME, SURNAME, V_NAME, V_SURNAME, DOB, EMAIL, M_F, ID_WS, REG_DATE, STATUS, ID_TOFI FROM RIS.R_WORKER;

INSERT INTO RIS.R_CV_P(ID_CV, PIN, NAME, CREATED_DATE, VISIBLE, STATUS) SELECT ID_CV, PIN, NAME, CREATED_DATE, VISIBLE, STATUS FROM RIS.R_CV;

INSERT INTO RIS.R_CV_EDU_HIST_P(ID_CEH, ID_CV, EIN, ID_EFT, ID_TIT, START_DATE, END_DATE, GRAD_DATE, CREATED_DATE, VISIBLE, STATUS)
SELECT ID_CEH, ID_CV, EIN, ID_EFT, ID_TIT, START_DATE, END_DATE, GRAD_DATE, CREATED_DATE, VISIBLE, STATUS FROM RIS.R_CV_EDU_HIST;

INSERT INTO RIS.R_CV_JOB_HIST_P(ID_CJH, ID_CV, CIN, ID_JT, ID_JP, START_DATE, END_DATE, VISIBLE, CREATED_DATE, STATUS)
SELECT ID_CJH, ID_CV, CIN, ID_JT, ID_JP, START_DATE, END_DATE, VISIBLE, CREATED_DATE, STATUS FROM RIS.R_CV_JOB_HIST;

INSERT INTO RIS.R_CV_JOB_REFERENCE_P(ID_CJR, ID_CJH, REF_TEXT, REF_PIN, ID_EVT, REF_DATE, STATUS)
SELECT ID_CJR, ID_CJH, REF_TEXT, REF_PIN, ID_EVT, REF_DATE, STATUS FROM RIS.R_CV_JOB_REFERENCE;
COMMIT;

DROP INDEX RIS.R_CVP_PIN_ID_CV_IDX;
DROP INDEX RIS.R_CEHP_ID_CEH_ID_CV_IDX;
CREATE INDEX RIS.R_CVP_PIN_ID_CV_IDX on RIS.R_CV_P(ID_CV, PIN) LOCAL TABLESPACE RIS_INDEX;
CREATE INDEX RIS.R_CEHP_ID_CEH_ID_CV_IDX on RIS.R_CV_EDU_HIST_P(ID_CEH, ID_CV) LOCAL TABLESPACE RIS_INDEX;


CREATE INDEX RIS.R_CVP_PIN_IDX on RIS.R_CV_P(PIN) LOCAL TABLESPACE RIS_INDEX;
CREATE INDEX RIS.R_CEHP_ID_CV_IDX on RIS.R_CV_EDU_HIST_P(ID_CV) LOCAL TABLESPACE RIS_INDEX;