PROMPT ##############################################################
PROMPT ########### - General Static Database - ######################
PROMPT ############### - CREATE TABLES - ############################
PROMPT ################# - COMPANY INDUSTRY - ############################

CREATE TABLE GSD.G_COMPANY_INDUSTRY
(
CIN number(16),               
ID_JI number(16),
CONSTRAINT G_CI_CIN_FK FOREIGN KEY (CIN)
	REFERENCES RIS.R_COMPANY (CIN),
CONSTRAINT G_CI_ID_JI_FK FOREIGN KEY (ID_JI)
    REFERENCES GSD.G_JOB_INDUSTRY (ID_JI)
)
TABLESPACE GSD_DATA;

COMMENT ON TABLE GSD.G_COMPANY_INDUSTRY IS 'Company Industry';
COMMENT ON COLUMN GSD.G_COMPANY_INDUSTRY.CIN IS 'FK - R_COMPANY - Company Identification Number';
COMMENT ON COLUMN GSD.G_COMPANY_INDUSTRY.ID_JI IS 'FK - G_JI - Industry of Company';

CREATE INDEX GSD.G_CI_ID_JI_IDX ON GSD.G_COMPANY_INDUSTRY (CIN, ID_JI) TABLESPACE GSD_INDEX;

PROMPT ########## - EDU_TYPES - #############################
CREATE TABLE GSD.G_EDU_TYPES
(
EIN number(16),
ID_EOT number(16),
CONSTRAINT G_ET_EIN_FK FOREIGN KEY (EIN)
	REFERENCES RIS.R_EDU_ORG (EIN),
CONSTRAINT G_ET_ID_EOT_FK FOREIGN KEY (ID_EOT)
	REFERENCES GSD.G_EDU_ORG_TYPE (ID_EOT)
)
TABLESPACE GSD_DATA;

COMMENT ON TABLE GSD.G_EDU_TYPES IS 'Education Organization';
COMMENT ON COLUMN GSD.G_EDU_TYPES.EIN IS 'FK - R_EDU_ORG - Education Organization Identification Number';
COMMENT ON COLUMN GSD.G_EDU_TYPES.ID_EOT IS 'FK - G_EOT - Edu Organization Type';

CREATE INDEX GSD.G_ET_ID_EOT_IDX ON GSD.G_EDU_TYPES (ID_EOT) TABLESPACE GSD_INDEX;

PROMPT ########## - EDU_ORG_FIELD - #############################

CREATE TABLE GSD.G_EDU_ORG_FIELD
(
EIN number(16),
ID_EFT number(16),
CONSTRAINT G_EOF_EIN_FK FOREIGN KEY (EIN)
	REFERENCES RIS.R_EDU_ORG (EIN),
CONSTRAINT G_EOF_ID_EFT_FK FOREIGN KEY (ID_EFT)
	REFERENCES GSD.G_EDU_FIELD_TYPE (ID_EFT)
)
TABLESPACE GSD_DATA;

COMMENT ON TABLE GSD.G_EDU_ORG_FIELD IS 'Fields of Education Organizations';
COMMENT ON COLUMN GSD.G_EDU_ORG_FIELD.EIN IS 'FK - R_EO - Education Organization Identification Number ';
COMMENT ON COLUMN GSD.G_EDU_ORG_FIELD.ID_EFT IS 'FK - G_EFT - Education Field Type';

CREATE INDEX GSD.G_EOF_ID_EFT ON GSD.G_EDU_ORG_FIELD (ID_EFT) TABLESPACE GSD_INDEX;

PROMPT ########## - SKILL_POSITION - #############################
CREATE TABLE GSD.G_SKILL_POSITION
(
NAME varchar(40),
ID_JP number(16),
CONSTRAINT G_SP_ID_JP_FK FOREIGN KEY (ID_JP)
	REFERENCES GSD.G_JOB_POSITION (ID_JP)
)
TABLESPACE GSD_DATA;

COMMENT ON TABLE GSD.G_SKILL_POSITION IS 'Skills for CVs for Positions';
COMMENT ON COLUMN GSD.G_SKILL_POSITION.NAME IS 'Name of skill';
COMMENT ON COLUMN GSD.G_SKILL_POSITION.ID_JP IS 'FK - G_JP - Job Position';

CREATE INDEX GSD.G_SP_ID_JP ON GSD.G_SKILL_POSITION (ID_JP) TABLESPACE GSD_INDEX;

