create or replace PACKAGE GSD.G_INS_GSD_PCK IS
PROCEDURE SP_JOB_TYPE          (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_JOB_INDUSTRY      (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_JOB_POSITION      (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_INDUSTRY_POSITION (id_ji NUMBER, id_jp NUMBER);
PROCEDURE SP_WORKER_STATUS     (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_EVALUATION        (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_TITLE             (name VARCHAR, long_name VARCHAR, fa VARCHAR, lvl NUMBER);
PROCEDURE SP_EDU_ORG_TYPE      (name VARCHAR, long_name VARCHAR, max NUMBER);
PROCEDURE SP_EDU_FIELD_TYPE    (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_EDU_ORG_FIELD	   (ein NUMBER, id_eft NUMBER);
PROCEDURE SP_EDU_TYPES         (ein NUMBER, id_eot NUMBER);
PROCEDURE SP_COMPANY_TYPE      (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_COMPANY_INDUSTRY  (cin NUMBER, id_ji NUMBER);
PROCEDURE SP_LANGUAGE          (name VARCHAR, long_name VARCHAR);
PROCEDURE SP_ORGANIZATION      (i_oin NUMBER, i_name VARCHAR, i_doe DATE, i_doi DATE, i_email VARCHAR);
PROCEDURE SP_TOFI              (id_tit NUMBER, id_eot NUMBER, id_eft NUMBER, id_jp NUMBER);
PROCEDURE SP_RULE_TYPES        (rule VARCHAR);
PROCEDURE SP_RULES             (rt NUMBER, min NUMBER, max NUMBER);
PROCEDURE SP_RULES             (rt NUMBER, val1 VARCHAR, val2 VARCHAR);
PROCEDURE SP_SKILL_POSITION    (name VARCHAR, id_jp NUMBER);
END;
/

create or replace PACKAGE BODY GSD.G_INS_GSD_PCK IS
PROCEDURE SP_JOB_TYPE         (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_JOB_TYPE(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_JOB_INDUSTRY     (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_JOB_INDUSTRY(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_JOB_POSITION      (name VARCHAR, long_name VARCHAR) IS
    id_ji NUMBER;
    BEGIN
        INSERT INTO G_JOB_POSITION (NAME, LONG_NAME, VALID_F) VALUES (name, long_name, SYSDATE); 
    END;
PROCEDURE SP_INDUSTRY_POSITION      (id_ji NUMBER, id_jp NUMBER) IS
    BEGIN
        INSERT INTO G_INDUSTRY_POSITION (ID_JI, ID_JP) VALUES (id_ji, id_jp);
    END;
PROCEDURE SP_WORKER_STATUS     (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_WORKER_STATUS(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_EVALUATION        (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_EVALUATION(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_TITLE             (name VARCHAR, long_name VARCHAR, fa VARCHAR, lvl NUMBER) IS
    BEGIN
        INSERT INTO G_TITLE(NAME, LONG_NAME, F_A, LVL, VALID_F) VALUES(name, long_name, fa, lvl, SYSDATE);
    END;
PROCEDURE SP_EDU_ORG_TYPE      (name VARCHAR, long_name VARCHAR, max NUMBER) IS
    BEGIN
        INSERT INTO G_EDU_ORG_TYPE(NAME, LONG_NAME, MAX_LVL, VALID_F) VALUES(name, long_name, max, SYSDATE);
    END;
PROCEDURE SP_EDU_FIELD_TYPE    (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_EDU_FIELD_TYPE(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_EDU_ORG_FIELD		(ein NUMBER, id_eft NUMBER) IS
	BEGIN
		INSERT INTO G_EDU_ORG_FIELD(EIN, ID_EFT) VALUES(ein, id_eft);
	END;
PROCEDURE SP_EDU_TYPES         (ein NUMBER, id_eot NUMBER) IS
BEGIN
    INSERT INTO G_EDU_TYPES (EIN, ID_EOT) VALUES (ein, id_eot);
END;
PROCEDURE SP_COMPANY_TYPE      (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_COMPANY_TYPE(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_COMPANY_INDUSTRY	(cin NUMBER, id_ji NUMBER) IS
	BEGIN
		INSERT INTO G_COMPANY_INDUSTRY(CIN, ID_JI) VALUES(cin, id_ji);
	END;
PROCEDURE SP_LANGUAGE          (name VARCHAR, long_name VARCHAR) IS
    BEGIN
        INSERT INTO G_LANGUAGE(NAME, LONG_NAME, VALID_F) VALUES(name, long_name, SYSDATE);
    END;
PROCEDURE SP_ORGANIZATION      (i_oin NUMBER, i_name VARCHAR, i_doe DATE, i_doi DATE, i_email VARCHAR) IS
    BEGIN
        INSERT INTO G_ORGANIZATION(OIN, NAME, DOE, DOI, EMAIL, REG_DATE, STATUS ) VALUES (i_oin, i_name, i_doe, i_doi, i_email, SYSDATE, 'A');
    END;
PROCEDURE SP_TOFI              (id_tit NUMBER, id_eot NUMBER, id_eft NUMBER, id_jp NUMBER) IS
    BEGIN
        INSERT INTO G_TOFI (ID_TIT, ID_EOT, ID_EFT, ID_JP) VALUES (id_tit, id_eot, id_eft, id_jp);
    END;
PROCEDURE SP_RULE_TYPES        (rule VARCHAR) IS
    BEGIN
        INSERT INTO G_RULE_TYPES(NAME) VALUES (rule);
    END;
PROCEDURE SP_RULES             (rt NUMBER, min NUMBER, max NUMBER) IS
    BEGIN
        INSERT INTO G_RULES (ID_RULT, MINI, MAXI) VALUES (rt, min, max);
    END;
PROCEDURE SP_RULES             (rt NUMBER, val1 VARCHAR, val2 VARCHAR) IS
    BEGIN  
        INSERT INTO G_RULES (ID_RULT, VALUE1, VALUE2) VALUES (rt, val1, val2);
    END;
PROCEDURE SP_SKILL_POSITION    (name VARCHAR, id_jp NUMBER) IS
	BEGIN
		INSERT INTO G_SKILL_POSITION(NAME, ID_JP) VALUES (name, id_jp);
	END;
END;
/
