----- These MViews are splitting G_ORGANIZATION Names of self-employed people into Name and Surname of R_WORKERS

CREATE MATERIALIZED VIEW GSD.G_M_NAME_BY_ORG_MV 
TABLESPACE GSD_DATA 
AS 
SELECT 
				smn.MEN_NAME, smn.MEN_NAME_V, sms.MEN_SURNAME, sms.MEN_SURNAME_V,
				ROW_NUMBER() OVER(ORDER BY org.OIN) RWN
			FROM 
				GSD.G_ORGANIZATION org, 
				GSD.SAMPLE_MEN_NAME smn, GSD.SAMPLE_MEN_SURNAME sms 
			WHERE
				smn.MEN_NAME||' '=REGEXP_SUBSTR(org.NAME,'[^ ]+ ')
				AND sms.MEN_SURNAME=SUBSTR(org.NAME, INSTR(org.NAME, ' ')+1)
			ORDER BY org.OIN;

EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname=>'GSD', tabname=>'G_M_NAME_BY_ORG_MV');
    
CREATE INDEX GSD.G_M_NAME_BY_ORG_RWN_IDX ON GSD.G_M_NAME_BY_ORG_MV (RWN) TABLESPACE GSD_DATA;

CREATE MATERIALIZED VIEW GSD.G_W_NAME_BY_ORG_MV
TABLESPACE GSD_DATA
AS 
SELECT 
    swn.WOMEN_NAME, swn.WOMEN_NAME_V, sws.WOMEN_SURNAME, sws.WOMEN_SURNAME_V,
    ROW_NUMBER() OVER(ORDER BY org.OIN) RWN
FROM 
    GSD.G_ORGANIZATION org, 
    GSD.SAMPLE_WOMEN_NAME swn, GSD.SAMPLE_WOMEN_SURNAME sws 
WHERE
    swn.WOMEN_NAME||' '=REGEXP_SUBSTR(org.NAME,'[^ ]+ ')
    AND sws.WOMEN_SURNAME=SUBSTR(org.NAME, INSTR(org.NAME, ' ')+1)
ORDER BY org.OIN;

EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname=>'GSD', tabname=>'G_W_NAME_BY_ORG_MV');
CREATE INDEX GSD.G_W_NAME_BY_ORG_RWN_IDX ON GSD.G_W_NAME_BY_ORG_MV (RWN) TABLESPACE GSD_DATA;

GRANT SELECT ON GSD.G_M_NAME_BY_ORG_MV TO RIS;
GRANT SELECT ON GSD.G_W_NAME_BY_ORG_MV TO RIS;
