CREATE OR REPLACE PROCEDURE RIS_DWH.DWH_LOG_SP(
    MODULE_IN IN varchar,
    OPERATION_IN IN varchar,
	STEP_IN IN varchar,
    STATUS_IN IN varchar
) IS
	PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
	INSERT INTO ETL_LOG(LOG_TIME, MODULE, OPERATION, STEP, STATUS) VALUES (SYSTIMESTAMP, MODULE_IN, OPERATION_IN, STEP_IN, STATUS_IN);
	COMMIT;
EXCEPTION
	WHEN OTHERS
		THEN
			DBMS_OUTPUT.PUT_LINE('Error logging: ' || SQLCODE || ' - ' || SQLERRM);
END;
/