CREATE PROCEDURE RIS_DWH.CREATE_DB_LINKS AS
BEGIN
    EXECUTE IMMEDIATE 'CREATE DATABASE LINK RIS_SRC CONNECT TO RIS IDENTIFIED BY "abcdefg" USING ''DMAN01''';
    EXECUTE IMMEDIATE 'CREATE DATABASE LINK GSD_SRC CONNECT TO GSD IDENTIFIED BY "abcdefg" USING ''DMAN01''';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore errors (e.g., link already exists)
END;
/

EXEC RIS_DWH.CREATE_DB_LINKS;

DROP PROCEDURE RIS_DWH.CREATE_DB_LINKS;