CREATE USER RIS_DWH IDENTIFIED BY "abcdefg" DEFAULT TABLESPACE RIS_DWH_DATA QUOTA UNLIMITED ON RIS_DWH_DATA;

ALTER USER RIS_DWH QUOTA UNLIMITED ON RIS_DWH_DATA;
ALTER USER RIS_DWH QUOTA UNLIMITED ON RIS_DWH_INDEX;

GRANT CONNECT TO RIS_DWH;
GRANT RESOURCE TO RIS_DWH;
GRANT CREATE DATABASE LINK TO RIS_DWH;